---
title: "Electricity Power Consumption"
author: "Rui Nascimento"
date: "06/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Electricity Power Consumption

## Importing the data

```{r}
library(data.table)
epc <- fread("API_EG.USE.ELEC.KH.PC_DS2_en_csv_v2_511946/API_EG.USE.ELEC.KH.PC_DS2_en_csv_v2_511946.csv", skip = 4, header = TRUE, check.names = TRUE)
head(epc)
str(epc)
```

## Clean up the data

```{r}
epc[, c("Indicator.Name", "Indicator.Code", "V65"):=NULL]
setnames(epc, c("Country.Name", "Country.Code"), c("Country", "Code"))
head(names(epc))
```

```{r}
PC <- melt(epc, id.vars = c("Country", "Code"), measure = patterns("^X"),
variable.name = "YearC", value.name = c("PCE"), na.rm = TRUE)
```

```{r}
structure(PC)
```

```{r}
PC[, `:=`(Year=as.numeric(gsub("[^[:digit:].]", "", YearC)))][, YearC:=NULL]
setcolorder(PC, c("Country", "Code", "Year",
"PCE"))
PC
```

# Exploratory Analysis
```{r}
PC[Country %in% "Portugal"]
```

# Portugal Electric Power Consuption

```{r}
library(ggplot2)
library(magrittr)
PC[Country %in% "Portugal"] %>%
  ggplot(aes(Year, PCE)) +
  geom_line() + geom_point() +
  scale_y_continuous() +
  ylab("% Power Consuption")
```

```{r}
PC[Country %in% c("Portugal", "European Union")] %>%
  ggplot(aes(Year, PCE, colour=Country)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks=seq(1960, 2015, 5)) +
  scale_y_continuous() +
  ggtitle("Portugal Power Consuption vs EU Countries") +
  ylab("% Power Consuption")
```

# Rank Countries by Power Consumption

```{r}
PC[order(PCE)]
PC <- PC[Country != "Sudan"]
```

```{r}
library(countrycode)
cl <- as.data.table(codelist)[, .(continent, wb)]
setnames(cl, c("continent", "wb"),c("Continent", "Code"))
cPC <- cl[PC, on="Code"]
cPC
```

```{r}
a2000 = cPC[Year == 2000, c("Country", "PCE")]
setnames(a2000, "PCE", "X2000")
diffPC <- merge(cPC, a2000, by = "Country")
diffPC
```

Calculate the percentage diference using year 2000 as a baseline

```{r}
diffPC[!is.na(Continent), pcDiff := round(100*(PCE - X2000)/X2000,0)][, X2000:=NULL]
diffPC
```

# Compare Portugal Cosuption

```{r}
library(gghighlight)
diffPC[Continent == "Europe"] %>%
ggplot(aes(Year, PCE, group=Country, colour=Country)) +
geom_line() +
gghighlight(Country=="Portugal",
use_direct_label = FALSE) +
scale_y_log10() +
ggtitle("Europe Power Consumption") +
ylab("% Power Consumption")
```

```{r}
library(gghighlight)
diffPC[Country %in% c("Portugal", "Sweden", "Spain", "Hungary", "Romania", "Finland", "Germany")] %>%
ggplot(aes(Year, pcDiff, group=Country, colour=Country)) +
geom_line() +
ggtitle("Europe Power Consumption") +
ylab("% Power Consumption")
```